# This file allows you to configure Airflow Connections, Pools, and Variables in a single place for local development only.
# NOTE: json dicts can be added to the conn_extra field as yaml key value pairs. See the example below.

# For more information, refer to our docs: https://www.astronomer.io/docs/astro/cli/develop-project#configure-airflow_settingsyaml-local-development-only
# For questions, reach out to: https://support.astronomer.io
# For issues create an issue ticket here: https://github.com/astronomer/astro-cli/issues

airflow:
  connections:
    - conn_id: psql_conn
      conn_type: postgres
      conn_host: postgres-db
      conn_schema: test_database
      conn_login: test_user
      conn_password: test_password1234
      conn_port: 5432

    - conn_id: minio_conn
      conn_type: aws
      login: ${MINIO_ROOT_USER}
      password: ${MINIO_ROOT_PASSWARD}
      conn_extra:
        - example_extra_field:
        - aws_access_key_id: ${MINIO_ROOT_USER}
        - aws_secret_access_key: ${MINIO_ROOT_PASSWARD}
        - host: "http://192.168.0.4:9000"
        - endpoint_url: "http://192.168.0.4:9000"


  pools:
    - pool_name:
      pool_slot:
      pool_description:
  variables:
    - variable_name:
      variable_value:
